-- Write a SQL script that creates a table users
DROP TABLE IF EXISTS users;
CREATE TABLE users
(   
    id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOTNULL,
    email VARCHAR(255) UNIQUE NOTNULL,
    name VARCHAR(255) UNIQUE NOTNULL,
);
